"""add geom column to cell_towers

Revision ID: cb4d44342414
Revises:
Create Date: 2025-10-28 03:10:33.907470

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = "cb4d44342414"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

from sqlalchemy import text


def upgrade():
    op.add_column(
        "cell_towers",
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(geometry_type="POINT", srid=4326),
            nullable=True,
        ),
    )

    # Only create index if it doesn't exist
    conn = op.get_bind()
    res = conn.execute(text("SELECT to_regclass('idx_cell_towers_geom');"))
    if not res.scalar():
        op.create_index(
            "idx_cell_towers_geom", "cell_towers", ["geom"], postgresql_using="gist"
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_cell_towers_geom", table_name="cell_towers", postgresql_using="gist"
    )
    op.drop_column("cell_towers", "geom")
    # ### end Alembic commands ###
